volumes:
  prometheus_data:
    name: prometheus
  grafana_data:
    name: grafana

networks:
  net:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus


  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    networks:
      - net
    volumes:
      - grafana_data:/var/lib/grafana